
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AppBanner': typeof import("../components/AppBanner.vue")['default']
    'AppBlog': typeof import("../components/AppBlog.vue")['default']
    'AppCompliment': typeof import("../components/AppCompliment.vue")['default']
    'AppContact': typeof import("../components/AppContact.vue")['default']
    'AppHeader': typeof import("../components/AppHeader.vue")['default']
    'AppProjects': typeof import("../components/AppProjects.vue")['default']
    'MediumCard': typeof import("../components/MediumCard.vue")['default']
    'MediumFeeds': typeof import("../components/MediumFeeds.vue")['default']
    'Project': typeof import("../components/Project.vue")['default']
    'UserAvatar': typeof import("../components/UserAvatar.vue")['default']
    'UserCompliment': typeof import("../components/UserCompliment.vue")['default']
    'IconsFigureFlower': typeof import("../components/icons/FigureFlower.vue")['default']
    'IconsFigureFrame': typeof import("../components/icons/FigureFrame.vue")['default']
    'IconsFigureFrameSection': typeof import("../components/icons/FigureFrameSection.vue")['default']
    'IconsIconArrowRight': typeof import("../components/icons/IconArrowRight.vue")['default']
    'IconsIconSocialFacebook': typeof import("../components/icons/IconSocialFacebook.vue")['default']
    'IconsIconSocialInstagram': typeof import("../components/icons/IconSocialInstagram.vue")['default']
    'IconsIconSocialLinkedIn': typeof import("../components/icons/IconSocialLinkedIn.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'SwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAppBanner': typeof import("../components/AppBanner.vue")['default']
    'LazyAppBlog': typeof import("../components/AppBlog.vue")['default']
    'LazyAppCompliment': typeof import("../components/AppCompliment.vue")['default']
    'LazyAppContact': typeof import("../components/AppContact.vue")['default']
    'LazyAppHeader': typeof import("../components/AppHeader.vue")['default']
    'LazyAppProjects': typeof import("../components/AppProjects.vue")['default']
    'LazyMediumCard': typeof import("../components/MediumCard.vue")['default']
    'LazyMediumFeeds': typeof import("../components/MediumFeeds.vue")['default']
    'LazyProject': typeof import("../components/Project.vue")['default']
    'LazyUserAvatar': typeof import("../components/UserAvatar.vue")['default']
    'LazyUserCompliment': typeof import("../components/UserCompliment.vue")['default']
    'LazyIconsFigureFlower': typeof import("../components/icons/FigureFlower.vue")['default']
    'LazyIconsFigureFrame': typeof import("../components/icons/FigureFrame.vue")['default']
    'LazyIconsFigureFrameSection': typeof import("../components/icons/FigureFrameSection.vue")['default']
    'LazyIconsIconArrowRight': typeof import("../components/icons/IconArrowRight.vue")['default']
    'LazyIconsIconSocialFacebook': typeof import("../components/icons/IconSocialFacebook.vue")['default']
    'LazyIconsIconSocialInstagram': typeof import("../components/icons/IconSocialInstagram.vue")['default']
    'LazyIconsIconSocialLinkedIn': typeof import("../components/icons/IconSocialLinkedIn.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'LazySwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AppBanner: typeof import("../components/AppBanner.vue")['default']
export const AppBlog: typeof import("../components/AppBlog.vue")['default']
export const AppCompliment: typeof import("../components/AppCompliment.vue")['default']
export const AppContact: typeof import("../components/AppContact.vue")['default']
export const AppHeader: typeof import("../components/AppHeader.vue")['default']
export const AppProjects: typeof import("../components/AppProjects.vue")['default']
export const MediumCard: typeof import("../components/MediumCard.vue")['default']
export const MediumFeeds: typeof import("../components/MediumFeeds.vue")['default']
export const Project: typeof import("../components/Project.vue")['default']
export const UserAvatar: typeof import("../components/UserAvatar.vue")['default']
export const UserCompliment: typeof import("../components/UserCompliment.vue")['default']
export const IconsFigureFlower: typeof import("../components/icons/FigureFlower.vue")['default']
export const IconsFigureFrame: typeof import("../components/icons/FigureFrame.vue")['default']
export const IconsFigureFrameSection: typeof import("../components/icons/FigureFrameSection.vue")['default']
export const IconsIconArrowRight: typeof import("../components/icons/IconArrowRight.vue")['default']
export const IconsIconSocialFacebook: typeof import("../components/icons/IconSocialFacebook.vue")['default']
export const IconsIconSocialInstagram: typeof import("../components/icons/IconSocialInstagram.vue")['default']
export const IconsIconSocialLinkedIn: typeof import("../components/icons/IconSocialLinkedIn.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAppBanner: typeof import("../components/AppBanner.vue")['default']
export const LazyAppBlog: typeof import("../components/AppBlog.vue")['default']
export const LazyAppCompliment: typeof import("../components/AppCompliment.vue")['default']
export const LazyAppContact: typeof import("../components/AppContact.vue")['default']
export const LazyAppHeader: typeof import("../components/AppHeader.vue")['default']
export const LazyAppProjects: typeof import("../components/AppProjects.vue")['default']
export const LazyMediumCard: typeof import("../components/MediumCard.vue")['default']
export const LazyMediumFeeds: typeof import("../components/MediumFeeds.vue")['default']
export const LazyProject: typeof import("../components/Project.vue")['default']
export const LazyUserAvatar: typeof import("../components/UserAvatar.vue")['default']
export const LazyUserCompliment: typeof import("../components/UserCompliment.vue")['default']
export const LazyIconsFigureFlower: typeof import("../components/icons/FigureFlower.vue")['default']
export const LazyIconsFigureFrame: typeof import("../components/icons/FigureFrame.vue")['default']
export const LazyIconsFigureFrameSection: typeof import("../components/icons/FigureFrameSection.vue")['default']
export const LazyIconsIconArrowRight: typeof import("../components/icons/IconArrowRight.vue")['default']
export const LazyIconsIconSocialFacebook: typeof import("../components/icons/IconSocialFacebook.vue")['default']
export const LazyIconsIconSocialInstagram: typeof import("../components/icons/IconSocialInstagram.vue")['default']
export const LazyIconsIconSocialLinkedIn: typeof import("../components/icons/IconSocialLinkedIn.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const LazySwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
