// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/10/2024, 14:10:55
const configMerger = require("C:/Users/ivann/Documents/projects/Tatjana Kirienko/kirienko-ssr/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/ivann/Documents/projects/Tatjana Kirienko/kirienko-ssr/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ivann/Documents/projects/Tatjana Kirienko/kirienko-ssr/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ivann/Documents/projects/Tatjana Kirienko/kirienko-ssr/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ivann/Documents/projects/Tatjana Kirienko/kirienko-ssr/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ivann/Documents/projects/Tatjana Kirienko/kirienko-ssr/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ivann/Documents/projects/Tatjana Kirienko/kirienko-ssr/plugins/**/*.{js,ts,mjs}","C:/Users/ivann/Documents/projects/Tatjana Kirienko/kirienko-ssr/composables/**/*.{js,ts,mjs}","C:/Users/ivann/Documents/projects/Tatjana Kirienko/kirienko-ssr/utils/**/*.{js,ts,mjs}","C:/Users/ivann/Documents/projects/Tatjana Kirienko/kirienko-ssr/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ivann/Documents/projects/Tatjana Kirienko/kirienko-ssr/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ivann/Documents/projects/Tatjana Kirienko/kirienko-ssr/app.config.{js,ts,mjs}"] }));

module.exports = config
